### ISSUE TITLE
Error handling for createHandyClient

### ISSUE THREAD

**Issue by AnandChowdhary** [mmkal/handy-redis#74]
Doing the following does **not** catch the error:

```ts
import { createHandyClient, IHandyRedis } from "handy-redis";

let client: IHandyRedis;
try {
  client = createHandyClient({
    url: "redis://This is an invalid URL"
  });
} catch (error) {
  console.log("GOT ERROR HERE");
}
```

Instead, it crashes the process with this message:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to example:6379 failed - getaddrinfo ENOTFOUND example example:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at RedisClient.on_error (/Users/anandchowdhary/Projects/o15y/staart/node_modules/redis/index.
js:406:14)
    at Socket.<anonymous> (/Users/anandchowdhary/Projects/o15y/staart/node_modules/redis/index.js
:279:14)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by AnandChowdhary** [comment]
**Update:** I should have been using the `retry_strategy` key for error handling, like this:

```ts
export const redis = createHandyClient({
  url: REDIS_URL,
  retry_strategy: options => {
    if (options.error && options.error.code === "ECONNREFUSED") {
      console.log("The server refused the connection");
    }

    if (options.total_retry_time > 1000 * 60 * 60) {
      console.log("Retry time exhausted");
    }

    if (options.attempt > 10) {
      console.log("Max number of attempts exceeded");
    }

    // Reconnect after this time
    return Math.min(options.attempt * 100, 3000);
  }
});
```
